/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;
import controller.CinemaController;
import controller.CineplexController;
import controller.MovieController;
import entity.Cinema;
import entity.Cineplex;
import entity.Movie;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import utils.Common;

/**
 *
 * @author Aloysius
 */
public class Search extends javax.swing.JFrame {
    
    /**
     * Creates new form Search
     */
    Map<String, Integer> cineplexMap = new HashMap<>();
    Map<String, Integer> cinemaMap;
    Map<String, Integer> movieMap;
    
    public Search() {
        initComponents();
        LinkedList<Cineplex> cineplexes = CineplexController.getCineplexList();
        for (Cineplex c: cineplexes) {
            cineplexMap.put(c.getName(), c.getId());
            cineplexComboBox.addItem(c.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cineplexComboBox = new javax.swing.JComboBox();
        logoLbl = new javax.swing.JLabel();
        cinemaComboBox = new javax.swing.JComboBox();
        selectCineplexLbl = new javax.swing.JLabel();
        selectCinemaLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOBLIMA App");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        cineplexComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cineplexComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(cineplexComboBox);
        cineplexComboBox.setBounds(20, 160, 350, 20);

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/moblima.png"))); // NOI18N
        getContentPane().add(logoLbl);
        logoLbl.setBounds(20, 0, 230, 130);

        cinemaComboBox.setEnabled(false);
        cinemaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinemaComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(cinemaComboBox);
        cinemaComboBox.setBounds(20, 210, 350, 20);

        selectCineplexLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selectCineplexLbl.setText("Select a cineplex to continue");
        getContentPane().add(selectCineplexLbl);
        selectCineplexLbl.setBounds(20, 140, 350, 15);

        selectCinemaLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selectCinemaLbl.setText("Select a cinema to continue");
        selectCinemaLbl.setEnabled(false);
        getContentPane().add(selectCinemaLbl);
        selectCinemaLbl.setBounds(20, 190, 350, 15);

        getAccessibleContext().setAccessibleName("Frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cineplexComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cineplexComboBoxActionPerformed
        // TODO add your handling code here:
        LinkedList<Cinema> cinemas = CinemaController.getCinemasByCineplexId(cineplexMap.get(cineplexComboBox.getSelectedItem()));
        cinemaComboBox.removeAllItems();
        cinemaMap = new HashMap<>();
        for (Cinema c: cinemas) {
            cineplexMap.put(c.getName(), c.getId());
            cinemaComboBox.addItem(c.getName());
        }
        cinemaComboBox.setEnabled(true);
        selectCinemaLbl.setEnabled(true);
    }//GEN-LAST:event_cineplexComboBoxActionPerformed

    private void cinemaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinemaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinemaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Common.initDB();
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cinemaComboBox;
    private javax.swing.JComboBox cineplexComboBox;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel selectCinemaLbl;
    private javax.swing.JLabel selectCineplexLbl;
    // End of variables declaration//GEN-END:variables
}
